version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - "8001:8001"
